name: 'CI: Build and Test'
on:
  workflow_call:
      # inputs:
      #   AWS_REGION:
      #     required: true
      #     type: string
      #   ECR:
      #     required: true
      #     type: string

      # secrets:
      #   AWS_ROLE:
      #     required: true
      #   GH_PAT:
      #     required: true          

jobs:

  Publish:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}

    steps:
    - name: Clone Repo
      uses: actions/checkout@v3
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1.7.0
      with:
        role-to-assume: ${{secrets.AWS_ROLE}}
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: ${{vars.AWS_REGION}}

    - name: Check Credentials
      run: |
        aws sts get-caller-identity

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      run: |
        docker build -t ${{vars.ECR}}:${{ github.sha }} .
        docker push ${{vars.ECR}}:${{ github.sha }}

  Update_CD:
    runs-on: ubuntu-latest
    steps:
    - name: Download Kustomize
      run: |
        mkdir -p $GITHUB_WORKSPACE/bin
        curl -o $GITHUB_WORKSPACE/bin/kustomize_v5.4.1_linux_amd64.tar.gz --location "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.4.1/kustomize_v5.4.1_linux_amd64.tar.gz"
        tar -xvzf $GITHUB_WORKSPACE/bin/kustomize_v5.4.1_linux_amd64.tar.gz
        chmod u+x $GITHUB_WORKSPACE/kustomize

    - name: Check out manifest
      uses: actions/checkout@v3
      with:
        repository: hkaibara/deployment-repo
        ref: main
        token: ${{ vars.GH_PAT }}
        
    - name: Update Manifest Image Tag
      run: |
        ls -l
        cd app1/env/test
        kustomize edit set image app-test=${{vars.ECR}}:${{ github.sha }}
        git config user.name hkaibara
        git config user.email hiroshi.kaibara.hk@gmail.com
        git add .
        git diff-index --quiet HEAD || git commit --message "Update Image"
        git push