name: 'Release_Version'
on:
  workflow_call:
    inputs:
      runner:
        type: string
        required: true
      checkout_ref:
        type: string
        required: true
    outputs:
      tag:
        value: ${{jobs.Release.outputs.release_tag}}
jobs:
  Release:
    outputs:
      release_tag: ${{steps.release.outputs.automatic_releases_tag}}
    runs-on: ${{inputs.runner}}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{inputs.checkout_ref}}
          fetch-depth: '0'
  
      - name: Check latest Tag
        uses: anothrNick/github-tag-action@v1
        id: bump
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_BRANCHES: prod
          INITIAL_VERSION: 1.0.0
          DEFAULT_BUMP: none

      - name: Release tag
        id: release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "${{steps.bump.outputs.tag}}"